name: Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.149.0
      - uses: taiga-family/ci/actions/setup/node@v1.149.0
      - run: npx nx run-many --target build --all --exclude=demo

  build-demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.149.0
      - uses: taiga-family/ci/actions/setup/node@v1.149.0
      - run: npx nx build-gh-pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
