name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: taiga-family/ci/actions/setup/variables@v1.176.0
      - uses: taiga-family/ci/actions/setup/node@v1.176.0
      - run: npx nx build-gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.5
        with:
          branch: gh-pages
          folder: dist/demo/browser
          silent: false
          clean: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
