name: Deploy / preview

on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: taiga-family/ci/actions/setup/variables@v1.172.0
      - uses: taiga-family/ci/actions/setup/node@v1.172.0
      - run: npm run build

      - name: Debug output
        run: tree dist/demo/browser -P '*.html'
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0.10.0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MASKITO }}
          projectId: maskito
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
