name: E2E
on: [pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cache-cypress
      UNIVERSAL_SERVER: http://localhost:4000
      STATIC_SERVER: http://localhost:8080
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build demo
        run: npm run build

      - name: Prerender demo
        run: npm run build:prerender

      - name: Serving static files
        run: |
          npm run serve:prerender & sleep 5
          curl -X GET -I -f "${{ env.STATIC_SERVER }}"

      - name: Run cypress / ssr / prerender
        run: npm run cy:run -- --spec "**/*.cy.ts" --config baseUrl="${{ env.STATIC_SERVER }}"

      - name: Build ssr server
        run: npm run build:ssr

      - name: Serving ssr server
        run: |
          npm run serve:ssr & sleep 5
          curl -X GET -I -f "${{ env.UNIVERSAL_SERVER }}"

      - name: Run cypress / ssr / universal
        run: npm run cy:run -- --spec "**/*.cy.ts" --config baseUrl="${{ env.UNIVERSAL_SERVER }}"

concurrency:
  group: integration-e2e-${{ github.head_ref }}
  cancel-in-progress: true
