name: Lint
on: [pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.166.0
      - uses: taiga-family/ci/actions/setup/node@v1.166.0
      - run: npm run typecheck

  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.166.0
      - uses: taiga-family/ci/actions/setup/node@v1.166.0
      - run: npm run cspell -- --no-progress

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@v1.166.0
      - uses: taiga-family/ci/actions/setup/node@v1.166.0
      - run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}
      - uses: taiga-family/ci/actions/auto/push@v1.166.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@v1.166.0
      - uses: taiga-family/ci/actions/setup/node@v1.166.0
      - run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/ci/actions/auto/push@v1.166.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@v1.166.0
      - uses: taiga-family/ci/actions/setup/node@v1.166.0
      - run: npm run lint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/ci/actions/auto/push@v1.166.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  result:
    needs: [typecheck, cspell, prettier, stylelint, eslint]
    runs-on: ubuntu-latest
    name: Lint result
    steps:
      - run: echo "Success"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
