name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.164.0
      - uses: taiga-family/ci/actions/setup/node@v1.164.0

      - name: Run tests
        run: npx nx run-many --target test --all --coverage

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-${{ github.workflow }}-${{ github.run_id }}
          path: coverage

  codecov:
    name: Collect coverage
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/download-artifact@v4.3.0
        with:
          name: coverage-${{ github.workflow }}-${{ github.run_id }}
          path: coverage

      - name: Display structure of coverage files
        run: tree -L 2 ./coverage -P 'lcov.info'

      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/core/
          flags: summary,core
          name: core
      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/kit/
          flags: summary,kit
          name: kit
      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/phone/
          flags: summary,phone
          name: phone
      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/angular/
          flags: summary,angular
          name: angular
      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/react/
          flags: summary,react
          name: react
      - uses: codecov/codecov-action@v5.5.1
        with:
          directory: ./coverage/vue/
          flags: summary,vue
          name: vue

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
